(* File auto-generated by obus-gen-interface, DO NOT EDIT. *)
open OBus_member
module Org_freedesktop_timedate1 : sig
  val interface : OBus_name.interface
  val m_ListTimezones : (unit, string list) Method.t
  val m_SetLocalRTC : (bool * bool * bool, unit) Method.t
  val m_SetNTP : (bool * bool, unit) Method.t
  val m_SetTime : (int64 * bool * bool, unit) Method.t
  val m_SetTimezone : (string * bool, unit) Method.t
  val p_CanNTP : (bool, [ `readable ]) Property.t
  val p_LocalRTC : (bool, [ `readable ]) Property.t
  val p_NTP : (bool, [ `readable ]) Property.t
  val p_NTPSynchronized : (bool, [ `readable ]) Property.t
  val p_RTCTimeUSec : (int64, [ `readable ]) Property.t
  val p_TimeUSec : (int64, [ `readable ]) Property.t
  val p_Timezone : (string, [ `readable ]) Property.t
  type 'a members = {
    m_ListTimezones : 'a OBus_object.t -> unit -> string list Lwt.t;
    m_SetLocalRTC : 'a OBus_object.t -> bool * bool * bool -> unit Lwt.t;
    m_SetNTP : 'a OBus_object.t -> bool * bool -> unit Lwt.t;
    m_SetTime : 'a OBus_object.t -> int64 * bool * bool -> unit Lwt.t;
    m_SetTimezone : 'a OBus_object.t -> string * bool -> unit Lwt.t;
    p_CanNTP : 'a OBus_object.t -> bool React.signal;
    p_LocalRTC : 'a OBus_object.t -> bool React.signal;
    p_NTP : 'a OBus_object.t -> bool React.signal;
    p_NTPSynchronized : 'a OBus_object.t -> bool React.signal;
    p_RTCTimeUSec : 'a OBus_object.t -> int64 React.signal;
    p_TimeUSec : 'a OBus_object.t -> int64 React.signal;
    p_Timezone : 'a OBus_object.t -> string React.signal;
  }
  val make : 'a members -> 'a OBus_object.interface
end
