open Base

class type tick_minor_js =
  object
    inherit Font.t_js
  end

class type tick_major_js =
  object
    inherit Font.t_js
  end

class type tick_common_js =
  object
    inherit Font.t_js
    (* FIXME add callback, to major and minor too *)
    method display  : bool Js.t Js.prop
    method reverse  : bool Js.t Js.prop
    method minor    : tick_minor_js Js.t Js.prop
    method major    : tick_major_js Js.t Js.prop
  end

(** The minorTick configuration defines options
 ** for the minor tick marks that are generated by the axis.
 ** Omitted options are inherited from ticks configuration.
 **)
class tick_minor () = object
  inherit [tick_minor_js] base_option ()
  inherit [tick_minor_js] Font.t { size   = 12
                                 ; color  = CSS.Color.rgb 102 102 102
                                 ; family = "'Helvetica Neue','Helvetica','Arial',sans-serif"
                                 ; style  = `Normal
                                 } ()
end

(** The majorTick configuration defines options
 ** for the major tick marks that are generated by the axis.
 ** Omitted options are inherited from ticks configuration.
 **)
class tick_major () = object
  inherit [tick_major_js] base_option ()
  inherit [tick_major_js] Font.t { size   = 12
                                 ; color  = CSS.Color.rgb 102 102 102
                                 ; family = "'Helvetica Neue','Helvetica','Arial',sans-serif"
                                 ; style  = `Normal
                                 } ()
end

(** The tick configuration defines options for the tick marks that are generated by the axis. **)
class virtual tick_common () =
        object(self)

          val mutable virtual obj : #tick_common_js Js.t
          inherit ['a] Font.t { size = 12
                              ; color = CSS.Color.rgb 102 102 102
                              ; family = "'Helvetica Neue','Helvetica','Arial',sans-serif"
                              ; style  = `Normal
                              } ()

          val minor = new tick_minor ()
          val major = new tick_major ()

          (** If true, show tick marks. **)
          method display : bool = Js.to_bool obj##.display
          method set_display x = obj##.display := Js.bool x

          (** Reverses order of tick labels. **)
          method reverse : bool = Js.to_bool obj##.reverse
          method set_reverse x = obj##.reverse := Js.bool x

          (** Minor ticks configuration. Omitted options are inherited from options above. **)
          method minor : tick_minor = minor (* FIXME make empty ? *)

          (** Major ticks configuration. Omitted options are inherited from options above. **)
          method major : tick_major = major

          initializer
            self#set_display true;
            self#set_reverse false

        end
