(* File auto-generated by obus-gen-interface, DO NOT EDIT. *)
open OBus_member
module Org_freedesktop_timesync1_Manager : sig
  val interface : OBus_name.interface
  val p_FallbackNTPServers : (string list, [ `readable ]) Property.t
  val p_Frequency : (int64, [ `readable ]) Property.t
  val p_LinkNTPServers : (string list, [ `readable ]) Property.t
  val p_NTPMessage : (int32 * int32 * int32 * int32 * int32 * int64 * int64 * string * int64 * int64 * int64 * int64 * bool * int64 * int64, [ `readable ]) Property.t
  val p_PollIntervalMaxUSec : (int64, [ `readable ]) Property.t
  val p_PollIntervalMinUSec : (int64, [ `readable ]) Property.t
  val p_PollIntervalUSec : (int64, [ `readable ]) Property.t
  val p_RootDistanceMaxUSec : (int64, [ `readable ]) Property.t
  val p_ServerAddress : (int32 * string, [ `readable ]) Property.t
  val p_ServerName : (string, [ `readable ]) Property.t
  val p_SystemNTPServers : (string list, [ `readable ]) Property.t
  type 'a members = {
    p_FallbackNTPServers : 'a OBus_object.t -> string list React.signal;
    p_Frequency : 'a OBus_object.t -> int64 React.signal;
    p_LinkNTPServers : 'a OBus_object.t -> string list React.signal;
    p_NTPMessage : 'a OBus_object.t -> (int32 * int32 * int32 * int32 * int32 * int64 * int64 * string * int64 * int64 * int64 * int64 * bool * int64 * int64) React.signal;
    p_PollIntervalMaxUSec : 'a OBus_object.t -> int64 React.signal;
    p_PollIntervalMinUSec : 'a OBus_object.t -> int64 React.signal;
    p_PollIntervalUSec : 'a OBus_object.t -> int64 React.signal;
    p_RootDistanceMaxUSec : 'a OBus_object.t -> int64 React.signal;
    p_ServerAddress : 'a OBus_object.t -> (int32 * string) React.signal;
    p_ServerName : 'a OBus_object.t -> string React.signal;
    p_SystemNTPServers : 'a OBus_object.t -> string list React.signal;
  }
  val make : 'a members -> 'a OBus_object.interface
end
