module Node = Node

module type Descriptor = sig
  val name : string

  val parse : Bitstring.t -> int -> Node.t list
end

let parse bs offset =
  match%bitstring bs with
  | {| tag    : 8
     ; length : 8
     ; body   : length * 8 : save_offset_to (off_1), bitstring
     ; rest   : -1 : save_offset_to (off_2), bitstring
     |}
    ->
      let (module Descriptor : Descriptor) =
        match tag with
        | 0x02 -> (module Video_stream)
        | 0x03 -> (module Audio_stream)
        | 0x04 -> (module Hierarchy)
        | 0x05 -> (module Registration)
        | 0x06 -> (module Data_stream_alignment)
        | 0x07 -> (module Target_background_grid)
        | 0x08 -> (module Video_window)
        | 0x09 -> (module Ca)
        | 0x0A -> (module Iso_639_language)
        | 0x0B -> (module System_clock)
        | 0x0C -> (module Multiplex_buffer_utilization)
        | 0x0D -> (module Copyright)
        | 0x0E -> (module Maximum_bitrate)
        | 0x0F -> (module Private_data_indicator)
        | 0x10 -> (module Smoothing_buffer)
        | 0x11 -> (module Std_descriptor)
        | 0x12 -> (module Ibp_descriptor)
        | 0x13 | 0x14 | 0x15 | 0x16 | 0x17 | 0x18 | 0x19 | 0x1A ->
            (module Unknown)
        | 0x1B -> (module Mpeg4_video)
        | 0x1C -> (module Mpeg4_audio)
        | 0x1D -> (module Iod)
        | 0x1E -> (module Sl)
        | 0x1F -> (module Fmc)
        | 0x20 -> (module Es_id)
        | 0x21 -> (module Mux_code)
        | 0x22 -> (module Fmx_buffer_size)
        | 0x23 -> (module Multiplex_buffer)
        | 0x24 -> (module Content_labelling)
        | 0x25 -> (module Metadata_pointer)
        | 0x26 -> (module Metadata)
        | 0x27 -> (module Metadata_std)
        | 0x28 -> (module Avc_video)
        | 0x29 -> (module Ipmp)
        | 0x2A -> (module Avc_hrd)
        | 0x2B -> (module Mpeg2_aac_audio)
        | 0x2C -> (module Flex_mux_timing)
        | 0x2D -> (module Mpeg4_text)
        | 0x2E -> (module Mpeg4_audio_ext)
        | 0x2F -> (module Aux_video_stream)
        | 0x30 -> (module Svc_ext)
        | 0x31 -> (module Mvc_ext)
        | 0x32 -> (module J2k_video)
        | 0x33 -> (module Mvc_operation_point)
        | 0x34 -> (module Mpeg2_stereo_format)
        | 0x35 -> (module Stereo_program_info)
        | 0x36 -> (module Stereo_video_info)
        | 0x37 -> (module Transport_profile)
        | 0x38 -> (module Hevc_video)
        | 0x39 | 0x3A | 0x3B | 0x3C | 0x3D | 0x3E -> (module Unknown)
        | 0x3F -> (module Extension_1)
        | 0x40 -> (module Network_name)
        | 0x41 -> (module Service_list)
        | 0x42 -> (module Stuffing)
        | 0x43 -> (module Satellite_delivery)
        | 0x44 -> (module Cable_delivery)
        | 0x45 -> (module Vbi_data)
        | 0x46 -> (module Vbi_teletext)
        | 0x47 -> (module Bouquet_name)
        | 0x48 -> (module Service)
        | 0x49 -> (module Country_availability)
        | 0x4A -> (module Linkage)
        | 0x4B -> (module Nvod_reference)
        | 0x4C -> (module Time_shifted_service)
        | 0x4D -> (module Short_event)
        | 0x4E -> (module Extended_event)
        | 0x4F -> (module Time_shifted_event)
        | 0x50 -> (module Component)
        | 0x51 -> (module Mosaic)
        | 0x52 -> (module Stream_identifier)
        | 0x53 -> (module Ca_identifier)
        | 0x54 -> (module Content)
        | 0x55 -> (module Parental_rating)
        | 0x56 -> (module Teletext)
        | 0x57 -> (module Telephone)
        | 0x58 -> (module Local_time_offset)
        | 0x59 -> (module Subtitling)
        | 0x5A -> (module Terrestrial_delivery)
        | 0x5B -> (module Multilingual_network)
        | 0x5C -> (module Multilingual_bouquet)
        | 0x5D -> (module Multilingual_service)
        | 0x5E -> (module Multilingual_component)
        | 0x5F -> (module Private_data_specifier)
        | 0x60 -> (module Service_move)
        | 0x61 -> (module Short_smoothing_buffer)
        | 0x62 -> (module Frequency_list)
        | 0x63 -> (module Partial_transport_stream)
        | 0x64 -> (module Data_broadcast)
        | 0x65 -> (module Scrambling)
        | 0x66 -> (module Data_broadcast_id)
        | 0x67 -> (module Transport_stream)
        | 0x68 -> (module Dsng)
        | 0x69 -> (module Pdc)
        | 0x6A -> (module Ac3)
        | 0x6B -> (module Ancillary_data)
        | 0x6C -> (module Cell_list)
        | 0x6D -> (module Cell_frequency_link)
        | 0x6E -> (module Announcement_support)
        | 0x6F -> (module Application_signalling)
        | 0x70 -> (module Adaptation_field_data)
        | 0x71 -> (module Service_identifier)
        | 0x72 -> (module Service_availability)
        | 0x73 -> (module Default_authority)
        | 0x74 -> (module Related_content)
        | 0x75 -> (module Tva_id)
        | 0x76 -> (module Content_identifier)
        | 0x77 -> (module Time_slice_fec_id)
        | 0x78 -> (module Ecm_repetition_rate)
        | 0x79 -> (module S2_satellite_delivery)
        | 0x7A -> (module Enhanced_ac3)
        | 0x7B -> (module Dts)
        | 0x7C -> (module Aac)
        | 0x7D -> (module Xait_location)
        | 0x7E -> (module Fta_content_management)
        | 0x7F -> (module Extension_2)
        | 0xFF -> (module Forbidden)
        | x when x > 0x7F && x < 0xFF -> (module User_defined)
        | _ -> (module Unknown)
      in
      let name, content =
        (Descriptor.name, Descriptor.parse body (offset + off_1))
      in
      let node =
        Node.make ~offset:(offset + off_1) length name (List content)
      in
      (node, rest, offset + off_2)
